[workspace]
channels = ["conda-forge"]
name = "bricksim-native"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.35" }

[tasks]
build-native = "scripts/build.sh release"
build-native-release = "scripts/build.sh release"
build-native-debug = "scripts/build.sh debug"
test-native-debug = "scripts/build.sh debug-tests"
test-native-release = "scripts/build.sh release-tests"

[dependencies]
cmake = "==4.2.3"
ninja = "==1.13.2"
clangxx = "==22.1.0"
clang-tools = "==22.1.0"
llvm-tools = "==22.1.0"
lld = "==22.1.0"
libstdcxx-devel_linux-64 = "==15.2.0"
libgcc-devel_linux-64 = "==15.2.0"
"7zip" = "==26.00"
patch = "==2.8"
wget = "==1.25.0"
unzip = "==6.0"
