from typing import Optional

def get_physx_joint_force_torque(
    sdf_path: str,
) -> Optional[tuple[tuple[float, float, float], tuple[float, float, float]]]: ...

def init_natives() -> bool: ...
def deinit_natives() -> bool: ...
