def init_natives() -> bool: ...
def deinit_natives() -> bool: ...

def create_brick(path: str, dimensions: tuple[int, int, int], color: tuple[int, int, int]) -> None: ...
def export_lego_topology(root_path: str) -> str: ...
