import argparse
import collections
import importlib.metadata
import importlib.util
import json
import os
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

import toml


GENERATOR_NAME = "bricksim.cli.type_configs"
ISAACLAB_SOURCE_PACKAGES = (
    "isaaclab",
    "isaaclab_assets",
    "isaaclab_mimic",
    "isaaclab_rl",
    "isaaclab_tasks",
)
TY_OVERLAY_TOP_LEVEL_PACKAGES = {"isaacsim"}
PACKAGE_MARKER = f"# Generated by {GENERATOR_NAME} for static analysis only.\n"
ISAACSIM_PACKAGE_MARKER = (
    f"# Generated by {GENERATOR_NAME} for static analysis only.\n"
    "from .simulation_app import AppFramework, SimulationApp\n"
)


@dataclass(frozen=True)
class TargetPaths:
    root: Path
    pyright_overlay_dir: Path
    ty_overlay_dir: Path
    pyright_base_config_path: Path
    pyright_deps_config_path: Path
    ty_config_path: Path


@dataclass(frozen=True)
class Operation:
    kind: str
    path: Path
    content: str | None = None
    target: Path | None = None


class OperationPlanner:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.operations: list[Operation] = []
        self._planned_dirs: set[Path] = set()
        self._planned_files: set[Path] = set()
        self._reset_roots: set[Path] = set()

    def plan_remove_dir(self, path: Path) -> None:
        if not path.exists():
            return
        self.operations.append(Operation("remove_dir", path))
        self._reset_roots.add(path)
        self._planned_dirs.discard(path)

    def plan_dir(self, path: Path) -> None:
        if path == path.parent:
            return
        if self._path_will_exist(path):
            return
        self.plan_dir(path.parent)
        self.operations.append(Operation("create_dir", path))
        self._planned_dirs.add(path)

    def plan_text_file(self, path: Path, content: str) -> None:
        self.plan_dir(path.parent)
        kind = "overwrite_file" if self._path_will_exist(path) else "create_file"
        self.operations.append(Operation(kind, path, content=content))
        self._planned_files.add(path)

    def plan_symlink(self, path: Path, target: Path) -> None:
        self.plan_dir(path.parent)
        if self._path_will_exist(path):
            return
        self.operations.append(Operation("create_link", path, target=target))
        self._planned_files.add(path)

    def _path_will_exist(self, path: Path) -> bool:
        if path in self._planned_dirs or path in self._planned_files:
            return True
        if self._is_reset(path):
            return False
        return path.exists()

    def _is_reset(self, path: Path) -> bool:
        return any(reset_root == path or reset_root in path.parents for reset_root in self._reset_roots)


def _resolve_target_paths(root: Path) -> TargetPaths:
    return TargetPaths(
        root=root,
        pyright_overlay_dir=root / ".pyright" / "extension-packages",
        ty_overlay_dir=root / ".ty" / "extension-packages",
        pyright_base_config_path=root / "pyrightconfig.base.json",
        pyright_deps_config_path=root / "pyrightconfig.deps.json",
        ty_config_path=root / "ty.toml",
    )


def _iter_subdirs(base: Path) -> Iterable[Path]:
    if not base.is_dir():
        return []
    for entry in base.iterdir():
        if entry.is_dir():
            yield entry


def _resolve_isaaclab_source_root() -> Path:
    spec = importlib.util.find_spec("isaaclab")
    if spec is None or spec.origin is None:
        raise RuntimeError("Required Python package not found: isaaclab")

    module_dir = Path(os.path.realpath(spec.origin)).parent

    nested_source_root = module_dir / "source"
    if (nested_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return nested_source_root.resolve()

    editable_source_root = module_dir.parent.parent
    if (editable_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return editable_source_root.resolve()

    raise RuntimeError(f"Unable to resolve Isaac Lab source root from {module_dir}")


def _resolve_bricksim_import_root_if_editable() -> Path | None:
    try:
        dist = importlib.metadata.distribution("bricksim")
    except importlib.metadata.PackageNotFoundError:
        return None

    try:
        direct_url = json.loads(dist.read_text("direct_url.json") or "{}")
    except Exception:
        return None

    if not direct_url.get("dir_info", {}).get("editable"):
        return None

    spec = importlib.util.find_spec("bricksim")
    if spec is None or spec.origin is None:
        return None

    module_dir = Path(os.path.realpath(spec.origin)).parent
    return module_dir.parent.resolve()


def collect_project_source_roots() -> list[Path]:
    roots: list[Path] = []
    bricksim_import_root = _resolve_bricksim_import_root_if_editable()
    if bricksim_import_root is not None:
        roots.append(bricksim_import_root)
    isaaclab_source_root = _resolve_isaaclab_source_root()
    for package_name in ISAACLAB_SOURCE_PACKAGES:
        roots.append((isaaclab_source_root / package_name).resolve())
    return roots


def _extract_python_module_entries_from_raw_toml(config_path: Path) -> list[dict[str, str]]:
    module_entries: list[dict[str, str]] = []
    current_entry: dict[str, str] | None = None
    for raw_line in config_path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if line == "[[python.module]]":
            if current_entry is not None:
                module_entries.append(current_entry)
            current_entry = {}
            continue
        if current_entry is not None:
            match = re.fullmatch(r'(name|path)\s*=\s*"([^"]*)"', line)
            if match is not None:
                current_entry[match.group(1)] = match.group(2)
                continue
        if current_entry is not None and line.startswith("["):
            module_entries.append(current_entry)
            current_entry = None
            continue
    if current_entry is not None:
        module_entries.append(current_entry)
    return module_entries


def _is_importable_root(path: Path) -> bool:
    if not path.is_dir():
        return False
    if any((path / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
        return True
    for entry in path.iterdir():
        if entry.is_dir() and any((entry / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
            return True
    return False


def _iter_top_level_importables(module_root: Path) -> Iterable[str]:
    if not module_root.is_dir():
        return []
    result: list[str] = []
    for entry in module_root.iterdir():
        if entry.name == "__pycache__" or entry.name.endswith((".dist-info", ".egg-info")):
            continue
        if entry.is_dir() and _is_importable_root(entry):
            result.append(entry.name)
        elif entry.is_file() and entry.suffix in (".py", ".pyi", ".so", ".pyd") and entry.stem != "__init__":
            result.append(entry.stem)
    return result


def _iter_extension_python_modules(ext_dir: Path) -> Iterable[tuple[Path, str]]:
    config_path = ext_dir / "config" / "extension.toml"
    if not config_path.is_file():
        return []
    try:
        config = toml.load(config_path)
        python_modules = config.get("python", {}).get("module", [])
        if isinstance(python_modules, dict):
            python_modules = [python_modules]
        module_entries = [item for item in python_modules if isinstance(item, dict)]
    except Exception:
        module_entries = _extract_python_module_entries_from_raw_toml(config_path)

    discovered_modules: list[tuple[Path, str]] = []
    seen: set[tuple[str, str]] = set()
    for entry in module_entries:
        module_root = (ext_dir / entry.get("path", ".")).resolve()
        module_name = entry.get("name", "")
        module_names = [module_name] if module_name else list(_iter_top_level_importables(module_root))
        for resolved_name in module_names:
            if not resolved_name or resolved_name.endswith(".tests"):
                continue
            key = (str(module_root), resolved_name)
            if key in seen:
                continue
            seen.add(key)
            discovered_modules.append((module_root, resolved_name))
    return discovered_modules


def _iter_parent_packages(module_name: str) -> Iterable[tuple[str, ...]]:
    parts = module_name.split(".")
    for depth in range(1, len(parts)):
        yield tuple(parts[:depth])


def _resolve_extension_module_path(module_root: Path, module_name: str) -> Path | None:
    parts = module_name.split(".")
    package_path = module_root.joinpath(*parts)
    if package_path.is_dir():
        return package_path

    module_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.py")
    if module_path.is_file():
        return module_path

    stub_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.pyi")
    if stub_path.is_file():
        return stub_path

    return None


def _overlay_init_content(package_parts: tuple[str, ...]) -> str:
    if package_parts == ("isaacsim",):
        return ISAACSIM_PACKAGE_MARKER
    return PACKAGE_MARKER


def _ensure_overlay_package(
    planner: OperationPlanner,
    overlay_dir: Path,
    package_parts: tuple[str, ...],
) -> Path:
    package_dir = overlay_dir.joinpath(*package_parts)
    planner.plan_dir(package_dir)
    init_path = package_dir / "__init__.py"
    if not planner._path_will_exist(init_path):
        planner.plan_text_file(init_path, _overlay_init_content(package_parts))
    return package_dir


def _mirror_extension_module(
    planner: OperationPlanner,
    module_root: Path,
    module_name: str,
    all_module_names: set[str],
    *,
    overlay_dir: Path,
) -> None:
    module_source = _resolve_extension_module_path(module_root, module_name)
    if module_source is None:
        return

    parts = module_name.split(".")
    for package_parts in _iter_parent_packages(module_name):
        _ensure_overlay_package(planner, overlay_dir, package_parts)

    if module_source.is_file():
        overlay_file = overlay_dir.joinpath(*parts[:-1], module_source.name)
        planner.plan_symlink(overlay_file, module_source)
        return

    target_dir = overlay_dir.joinpath(*parts)
    planner.plan_dir(target_dir)
    for entry in module_source.iterdir():
        if entry.name == "__pycache__":
            continue
        if entry.is_dir():
            child_module_name = f"{module_name}.{entry.name}"
            if any(
                candidate == child_module_name or candidate.startswith(f"{child_module_name}.")
                for candidate in all_module_names
            ):
                continue
        elif entry.suffix == ".py" and entry.stem != "__init__":
            child_module_name = f"{module_name}.{entry.stem}"
        else:
            child_module_name = ""
        if child_module_name and child_module_name in all_module_names:
            continue
        planner.plan_symlink(target_dir / entry.name, entry)

    init_path = target_dir / "__init__.py"
    if not planner._path_will_exist(init_path):
        planner.plan_text_file(init_path, _overlay_init_content(tuple(parts)))


def collect_isaacsim_extension_paths() -> list[Path]:
    import isaacsim

    isaacsim_path = Path(os.path.realpath(isaacsim.__file__)).parent
    paths: list[Path] = []

    kit_path = isaacsim_path / "kit"

    kernel_py = kit_path / "kernel" / "py"
    if kernel_py.is_dir():
        paths.append(kernel_py)

    for folder in ("exts", "extscore"):
        base = kit_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    for folder in ("exts", "extscache", "extsDeprecated", "extsUser"):
        base = isaacsim_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    ov_base = Path.home() / ".local" / "share" / "ov" / "data" / "Kit"
    if ov_base.is_dir():
        for kit_dir in ov_base.iterdir():
            if not kit_dir.is_dir():
                continue
            for exts_root in kit_dir.rglob("exts"):
                if not exts_root.is_dir():
                    continue
                for layer_dir in exts_root.iterdir():
                    if not layer_dir.is_dir():
                        continue
                    for ext_dir in layer_dir.iterdir():
                        if ext_dir.is_dir():
                            paths.append(ext_dir)

    seen: set[str] = set()
    result: list[Path] = []
    for path in paths:
        normalized = path.resolve()
        normalized_str = str(normalized)
        if normalized_str in seen:
            continue
        seen.add(normalized_str)
        result.append(normalized)
    return result


def _relative_or_absolute(path: Path, root: Path) -> str:
    try:
        return f"./{path.relative_to(root).as_posix()}"
    except ValueError:
        return path.as_posix()


def build_overlay(
    planner: OperationPlanner,
    extension_paths: Iterable[Path],
    overlay_dir: Path,
    *,
    include_module: Callable[[str], bool],
) -> str:
    extension_modules: list[tuple[Path, str]] = []
    module_names: set[str] = set()
    for ext_path in extension_paths:
        for module_root, module_name in _iter_extension_python_modules(ext_path):
            if not include_module(module_name):
                continue
            module_names.add(module_name)
            extension_modules.append((module_root, module_name))

    planner.plan_remove_dir(overlay_dir)
    planner.plan_dir(overlay_dir)

    for module_root, module_name in extension_modules:
        _mirror_extension_module(planner, module_root, module_name, module_names, overlay_dir=overlay_dir)

    return _relative_or_absolute(overlay_dir, planner.root)


def render_ty_config(*, python_path: str, ty_roots: list[str], ty_extra_paths: list[str]) -> str:
    lines = [
        f"# Generated by {GENERATOR_NAME} for static analysis only.",
        "",
        "[environment]",
        f'python = "{python_path}"',
    ]

    lines.append("root = [")
    for path in ty_roots:
        lines.append(f'    "{path}",')
    lines.append("]")

    lines.append("extra-paths = [")
    for path in ty_extra_paths:
        lines.append(f'    "{path}",')
    lines.append("]")

    return "\n".join(lines) + "\n"


def _active_python_environment_path(root: Path) -> str:
    return _relative_or_absolute(Path(sys.prefix).resolve(), root)


def plan_operations(paths: TargetPaths) -> tuple[list[Operation], str, str]:
    planner = OperationPlanner(paths.root)

    project_source_roots = collect_project_source_roots()
    isaacsim_extension_paths = collect_isaacsim_extension_paths()

    pyright_overlay_path = build_overlay(
        planner,
        isaacsim_extension_paths,
        paths.pyright_overlay_dir,
        include_module=lambda _: True,
    )
    ty_overlay_path = build_overlay(
        planner,
        isaacsim_extension_paths,
        paths.ty_overlay_dir,
        include_module=lambda module_name: module_name.split(".", 1)[0] in TY_OVERLAY_TOP_LEVEL_PACKAGES,
    )

    if not paths.pyright_base_config_path.exists():
        planner.plan_text_file(paths.pyright_base_config_path, "{}")

    pyright_extra_paths = [
        pyright_overlay_path,
        *(_relative_or_absolute(path, paths.root) for path in project_source_roots),
        *(_relative_or_absolute(path, paths.root) for path in isaacsim_extension_paths),
    ]
    pyright_deps_config = {
        "extends": "pyrightconfig.base.json",
        "extraPaths": pyright_extra_paths,
    }
    pyright_deps_config_text = json.dumps(pyright_deps_config, indent=4)
    planner.plan_text_file(paths.pyright_deps_config_path, pyright_deps_config_text)

    ty_roots = [_relative_or_absolute(path, paths.root) for path in project_source_roots]
    ty_extra_paths = [_relative_or_absolute(path, paths.root) for path in isaacsim_extension_paths]
    ty_extra_paths.insert(0, ty_overlay_path)
    ty_config_text = render_ty_config(
        python_path=_active_python_environment_path(paths.root),
        ty_roots=ty_roots,
        ty_extra_paths=ty_extra_paths,
    )
    planner.plan_text_file(paths.ty_config_path, ty_config_text)

    return planner.operations, pyright_deps_config_text, ty_config_text


def _format_operation(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix() or "."
    except ValueError:
        return path.as_posix()


def _overlay_bucket(path: Path, root: Path) -> str | None:
    try:
        relative_parts = path.relative_to(root).parts
    except ValueError:
        return None
    if len(relative_parts) >= 2 and relative_parts[0] in {".pyright", ".ty"} and relative_parts[1] == "extension-packages":
        return f"{relative_parts[0]}/{relative_parts[1]}"
    return None


def _log_single_operation(operation: Operation, root: Path, *, dry_run: bool) -> None:
    prefix = "Would " if dry_run else ""
    display_path = _format_operation(operation.path, root)
    if operation.kind == "remove_dir":
        print(f"{prefix}remove dir {display_path}")
    elif operation.kind == "create_dir":
        print(f"{prefix}create dir {display_path}")
    elif operation.kind == "create_file":
        print(f"{prefix}create file {display_path}")
    elif operation.kind == "overwrite_file":
        print(f"{prefix}overwrite file {display_path}")
    elif operation.kind == "create_link":
        assert operation.target is not None
        print(f"{prefix}create link {display_path} -> {operation.target.as_posix()}")
    else:
        raise RuntimeError(f"Unknown operation kind: {operation.kind}")


def _log_operations(
    operations: list[Operation],
    root: Path,
    *,
    dry_run: bool,
    verbose: bool,
) -> None:
    if verbose:
        for operation in operations:
            _log_single_operation(operation, root, dry_run=dry_run)
        return

    overlay_counts: dict[str, collections.Counter[str]] = {}
    for operation in operations:
        bucket = _overlay_bucket(operation.path, root)
        if bucket is None:
            _log_single_operation(operation, root, dry_run=dry_run)
            continue
        if bucket not in overlay_counts:
            overlay_counts[bucket] = collections.Counter()
        overlay_counts[bucket][operation.kind] += 1

    prefix = "Would update" if dry_run else "Updated"
    ordered_kinds = ("remove_dir", "create_dir", "create_file", "overwrite_file", "create_link")
    for bucket in sorted(overlay_counts):
        summary = " ".join(
            f"{kind}={overlay_counts[bucket][kind]}"
            for kind in ordered_kinds
            if overlay_counts[bucket][kind]
        )
        print(f"{prefix} {bucket}: {summary}")


def _apply_operations(operations: list[Operation]) -> None:
    for operation in operations:
        if operation.kind == "remove_dir":
            shutil.rmtree(operation.path)
        elif operation.kind == "create_dir":
            operation.path.mkdir(parents=True, exist_ok=True)
        elif operation.kind in {"create_file", "overwrite_file"}:
            assert operation.content is not None
            operation.path.write_text(operation.content, encoding="utf-8")
        elif operation.kind == "create_link":
            assert operation.target is not None
            operation.path.symlink_to(operation.target)
        else:
            raise RuntimeError(f"Unknown operation kind: {operation.kind}")


def _confirm_operations(root: Path, operations: list[Operation], *, verbose: bool) -> bool:
    print(f"Target root: {root.as_posix()}")
    _log_operations(operations, root, dry_run=True, verbose=verbose)
    if not sys.stdin.isatty():
        raise RuntimeError("Refusing to write without confirmation on a non-interactive stdin. Pass -y to apply non-interactively.")
    response = input("Apply these changes? [y/N]: ").strip().lower()
    return response in {"y", "yes"}


def main() -> int:
    parser = argparse.ArgumentParser(description="Collect Isaac Sim / Omniverse python paths for Pyright and ty.")
    parser.add_argument("-y", action="store_true", help="Apply changes without interactive confirmation.")
    parser.add_argument("-v", "--verbose", action="store_true", help="Print detailed changes inside .pyright and .ty.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated pyrightconfig.deps.json and ty.toml content without writing them.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("."),
        help="Target project root where configuration files should be written (default: current directory).",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    paths = _resolve_target_paths(root)
    operations, pyright_deps_config_text, ty_config_text = plan_operations(paths)

    if args.dry_run:
        _log_operations(operations, root, dry_run=True, verbose=args.verbose)
        print("=== pyrightconfig.deps.json ===")
        print(pyright_deps_config_text)
        print()
        print("=== ty.toml ===")
        print(ty_config_text, end="")
        return 0

    if not args.y and not _confirm_operations(root, operations, verbose=args.verbose):
        print("Aborted.")
        return 1

    _apply_operations(operations)
    _log_operations(operations, root, dry_run=False, verbose=args.verbose)
    print(f"Wrote {paths.pyright_deps_config_path}")
    print(f"Wrote {paths.ty_config_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
