[package]
version = "0.1.0"
title = "BrickSim"
description = "BrickSim Simulator"
repository = "https://github.com/intelligent-control-lab/BrickSim.git"
category = "isaaclab"
keywords = ["lego", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}

[core]
reloadable = true

[[python.module]]
name = "bricksim"
path = "../../.."
