def init_natives() -> bool: ...
def deinit_natives() -> bool: ...

def create_brick_prim(path: str, dimensions: tuple[int, int, int], color: tuple[int, int, int]) -> None: ...
def allocate_brick(dimensions: tuple[int, int, int], color: tuple[int, int, int], env_id: int) -> tuple[int, str]: ...
def deallocate_brick(brick_id: int, env_id: int) -> bool: ...
def deallocate_all_bricks_in_env(env_id: int) -> bool: ...
def export_lego_topology(root_path: str) -> str: ...

class LegoThresholds:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    distance_tolerance: float
    max_penetration: float
    z_angle_tolerance: float
    required_force: float
    yaw_tolerance: float
    position_tolerance: float
def get_lego_thresholds() -> LegoThresholds: ...
def set_lego_thresholds(thresholds: LegoThresholds) -> None: ...
