#!/usr/bin/env python3
import argparse
import json
import os
import re
import shutil
from pathlib import Path
from typing import Iterable

import toml


REPO_ROOT = Path(__file__).resolve().parent.parent
PYRIGHT_OVERLAY_DIR = REPO_ROOT / ".pyright" / "extension-packages"
PYRIGHT_OVERLAY_RELATIVE = PYRIGHT_OVERLAY_DIR.relative_to(REPO_ROOT).as_posix()
PACKAGE_MARKER = "# Generated by scripts/generate_pyrightconfig.py for static analysis only.\n"
ISAACSIM_PACKAGE_MARKER = """# Generated by scripts/generate_pyrightconfig.py for static analysis only.
from .simulation_app import AppFramework, SimulationApp
"""


def _iter_subdirs(base: Path) -> Iterable[Path]:
    if not base.is_dir():
        return []
    for entry in base.iterdir():
        if entry.is_dir():
            yield entry


def _extract_python_module_entries_from_raw_toml(config_path: Path) -> list[dict[str, str]]:
    module_entries: list[dict[str, str]] = []
    current_entry: dict[str, str] | None = None
    for raw_line in config_path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if line == "[[python.module]]":
            if current_entry is not None:
                module_entries.append(current_entry)
            current_entry = {}
            continue
        if current_entry is not None:
            match = re.fullmatch(r'(name|path)\s*=\s*"([^"]*)"', line)
            if match is not None:
                current_entry[match.group(1)] = match.group(2)
                continue
        if current_entry is not None and line.startswith("["):
            module_entries.append(current_entry)
            current_entry = None
            continue
    if current_entry is not None:
        module_entries.append(current_entry)
    return module_entries


def _is_importable_root(path: Path) -> bool:
    if not path.is_dir():
        return False
    if any((path / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
        return True
    for entry in path.iterdir():
        if entry.is_dir() and any((entry / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
            return True
    return False


def _iter_top_level_importables(module_root: Path) -> Iterable[str]:
    if not module_root.is_dir():
        return []
    result: list[str] = []
    for entry in module_root.iterdir():
        if entry.name == "__pycache__" or entry.name.endswith((".dist-info", ".egg-info")):
            continue
        if entry.is_dir() and _is_importable_root(entry):
            result.append(entry.name)
        elif entry.is_file() and entry.suffix in (".py", ".pyi", ".so", ".pyd") and entry.stem != "__init__":
            result.append(entry.stem)
    return result


def _iter_extension_python_modules(ext_dir: Path) -> Iterable[tuple[Path, str]]:
    config_path = ext_dir / "config" / "extension.toml"
    if not config_path.is_file():
        return []
    try:
        config = toml.load(config_path)
        python_modules = config.get("python", {}).get("module", [])
        if isinstance(python_modules, dict):
            python_modules = [python_modules]
        module_entries = [item for item in python_modules if isinstance(item, dict)]
    except Exception:
        module_entries = _extract_python_module_entries_from_raw_toml(config_path)

    discovered_modules: list[tuple[Path, str]] = []
    seen: set[tuple[str, str]] = set()
    for entry in module_entries:
        module_root = (ext_dir / entry.get("path", ".")).resolve()
        module_name = entry.get("name", "")
        module_names = [module_name] if module_name else list(_iter_top_level_importables(module_root))
        for resolved_name in module_names:
            if not resolved_name or resolved_name.endswith(".tests"):
                continue
            key = (str(module_root), resolved_name)
            if key in seen:
                continue
            seen.add(key)
            discovered_modules.append((module_root, resolved_name))
    return discovered_modules


def _iter_parent_packages(module_name: str) -> Iterable[tuple[str, ...]]:
    parts = module_name.split(".")
    for depth in range(1, len(parts)):
        yield tuple(parts[:depth])


def _resolve_extension_module_path(module_root: Path, module_name: str) -> Path | None:
    parts = module_name.split(".")
    package_path = module_root.joinpath(*parts)
    if package_path.is_dir():
        return package_path

    module_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.py")
    if module_path.is_file():
        return module_path

    stub_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.pyi")
    if stub_path.is_file():
        return stub_path

    return None


def _ensure_overlay_package(package_parts: tuple[str, ...]) -> Path:
    package_dir = PYRIGHT_OVERLAY_DIR.joinpath(*package_parts)
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(ISAACSIM_PACKAGE_MARKER if package_parts == ("isaacsim",) else PACKAGE_MARKER)
    return package_dir


def _symlink_path(src: Path, dst: Path) -> None:
    if dst.is_symlink():
        if dst.resolve() == src.resolve():
            return
        dst.unlink()
    elif dst.exists():
        return
    dst.symlink_to(src)


def _mirror_extension_module(module_root: Path, module_name: str, all_module_names: set[str]) -> None:
    module_source = _resolve_extension_module_path(module_root, module_name)
    if module_source is None:
        return

    parts = module_name.split(".")
    for package_parts in _iter_parent_packages(module_name):
        _ensure_overlay_package(package_parts)

    if module_source.is_file():
        overlay_file = PYRIGHT_OVERLAY_DIR.joinpath(*parts[:-1], module_source.name)
        overlay_file.parent.mkdir(parents=True, exist_ok=True)
        _symlink_path(module_source, overlay_file)
        return

    overlay_dir = PYRIGHT_OVERLAY_DIR.joinpath(*parts)
    overlay_dir.mkdir(parents=True, exist_ok=True)
    for entry in module_source.iterdir():
        if entry.name == "__pycache__":
            continue
        if entry.is_dir():
            child_module_name = f"{module_name}.{entry.name}"
        elif entry.suffix == ".py" and entry.stem != "__init__":
            child_module_name = f"{module_name}.{entry.stem}"
        else:
            child_module_name = ""
        if child_module_name and child_module_name in all_module_names:
            continue
        _symlink_path(entry, overlay_dir / entry.name)

    init_path = overlay_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(PACKAGE_MARKER)


def collect_isaacsim_extension_paths() -> list[str]:
    import isaacsim  # must be importable from the current venv

    isaacsim_path = Path(os.path.realpath(isaacsim.__file__)).parent
    paths: list[Path] = []

    # Kit side (mirrors isaacsim.__main__.generate_vscode_settings)
    kit_path = isaacsim_path / "kit"

    kernel_py = kit_path / "kernel" / "py"
    if kernel_py.is_dir():
        paths.append(kernel_py)

    for folder in ("exts", "extscore"):
        base = kit_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    # Isaac Sim side
    for folder in ("exts", "extscache", "extsDeprecated", "extsUser"):
        base = isaacsim_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    # Omniverse global extensions (where many omni.* packages live)
    ov_base = Path.home() / ".local" / "share" / "ov" / "data" / "Kit"
    if ov_base.is_dir():
        # Example layout:
        # ~/.local/share/ov/data/Kit/Isaac-Sim Full/5.1/exts/3/omni.usd-...
        for kit_dir in ov_base.iterdir():
            if not kit_dir.is_dir():
                continue
            # Look for any nested "exts" directories (depth >= 1).
            for exts_root in kit_dir.rglob("exts"):
                if not exts_root.is_dir():
                    continue
                for layer_dir in exts_root.iterdir():
                    if not layer_dir.is_dir():
                        continue
                    for ext_dir in layer_dir.iterdir():
                        if ext_dir.is_dir():
                            paths.append(ext_dir)

    # Deduplicate and normalize
    seen: set[str] = set()
    result: list[str] = []
    for p in paths:
        s = str(p.resolve())
        if s not in seen:
            seen.add(s)
            result.append(s)
    return result


def build_pyright_overlay(extension_paths: Iterable[str], *, dry_run: bool) -> str:
    extension_modules: list[tuple[Path, str]] = []
    module_names: set[str] = set()
    for ext_path in extension_paths:
        ext_dir = Path(ext_path)
        for module_root, module_name in _iter_extension_python_modules(ext_dir):
            module_names.add(module_name)
            extension_modules.append((module_root, module_name))

    if dry_run:
        return PYRIGHT_OVERLAY_RELATIVE

    if PYRIGHT_OVERLAY_DIR.exists():
        shutil.rmtree(PYRIGHT_OVERLAY_DIR)
    PYRIGHT_OVERLAY_DIR.mkdir(parents=True, exist_ok=True)

    for module_root, module_name in extension_modules:
        _mirror_extension_module(module_root, module_name, module_names)

    return PYRIGHT_OVERLAY_RELATIVE


def main() -> None:
    parser = argparse.ArgumentParser(description="Collect Isaac Sim / Omniverse python paths for pyright.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated pyrightconfig.deps.json content without writing it.",
    )
    args = parser.parse_args()

    extra_paths = [
        "exts/bricksim",
        "IsaacLab/source/isaaclab",
        "IsaacLab/source/isaaclab_assets",
        "IsaacLab/source/isaaclab_mimic",
        "IsaacLab/source/isaaclab_rl",
        "IsaacLab/source/isaaclab_tasks",
    ]
    isaacsim_extension_paths = collect_isaacsim_extension_paths()
    extra_paths.insert(0, build_pyright_overlay(isaacsim_extension_paths, dry_run=args.dry_run))
    extra_paths += isaacsim_extension_paths

    deps_config = {
        "extends": "pyrightconfig.base.json",
        "extraPaths": extra_paths,
    }

    if args.dry_run:
        print(json.dumps(deps_config, indent=4))
        return

    deps_config_path = REPO_ROOT / "pyrightconfig.deps.json"
    with deps_config_path.open("w") as f:
        json.dump(deps_config, f, indent=4)
    print(f"Wrote {deps_config_path}")


if __name__ == "__main__":
    main()
