#!/usr/bin/env python3
import argparse
import importlib.util
import json
import os
import re
import shutil
from pathlib import Path
from typing import Callable, Iterable

import toml


REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_RELATIVE_PATH = Path(__file__).resolve().relative_to(REPO_ROOT).as_posix()
PYRIGHT_OVERLAY_DIR = REPO_ROOT / ".pyright" / "extension-packages"
TY_OVERLAY_DIR = REPO_ROOT / ".ty" / "extension-packages"
PYRIGHT_DEPS_CONFIG_PATH = REPO_ROOT / "pyrightconfig.deps.json"
TY_CONFIG_PATH = REPO_ROOT / "ty.toml"
LOCAL_SOURCE_ROOTS = [
    Path("exts/bricksim"),
]
ISAACLAB_SOURCE_PACKAGES = ("isaaclab", "isaaclab_assets", "isaaclab_mimic", "isaaclab_rl", "isaaclab_tasks")
TY_OVERLAY_TOP_LEVEL_PACKAGES = {"isaacsim"}
PACKAGE_MARKER = f"# Generated by {SCRIPT_RELATIVE_PATH} for static analysis only.\n"
ISAACSIM_PACKAGE_MARKER = f"""# Generated by {SCRIPT_RELATIVE_PATH} for static analysis only.
from .simulation_app import AppFramework, SimulationApp
"""


def _iter_subdirs(base: Path) -> Iterable[Path]:
    if not base.is_dir():
        return []
    for entry in base.iterdir():
        if entry.is_dir():
            yield entry


def _resolve_isaaclab_source_root() -> Path:
    spec = importlib.util.find_spec("isaaclab")
    if spec is None or spec.origin is None:
        raise RuntimeError("Required Python package not found: isaaclab")

    module_dir = Path(os.path.realpath(spec.origin)).parent

    nested_source_root = module_dir / "source"
    if (nested_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return nested_source_root.resolve()

    editable_source_root = module_dir.parent.parent
    if (editable_source_root / "isaaclab" / "config" / "extension.toml").is_file():
        return editable_source_root.resolve()

    raise RuntimeError(f"Unable to resolve Isaac Lab source root from {module_dir}")


def collect_project_source_roots() -> list[Path]:
    roots = [*LOCAL_SOURCE_ROOTS]
    isaaclab_source_root = _resolve_isaaclab_source_root()
    for package_name in ISAACLAB_SOURCE_PACKAGES:
        roots.append((isaaclab_source_root / package_name).resolve())
    return roots


def _extract_python_module_entries_from_raw_toml(config_path: Path) -> list[dict[str, str]]:
    module_entries: list[dict[str, str]] = []
    current_entry: dict[str, str] | None = None
    for raw_line in config_path.read_text().splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if line == "[[python.module]]":
            if current_entry is not None:
                module_entries.append(current_entry)
            current_entry = {}
            continue
        if current_entry is not None:
            match = re.fullmatch(r'(name|path)\s*=\s*"([^"]*)"', line)
            if match is not None:
                current_entry[match.group(1)] = match.group(2)
                continue
        if current_entry is not None and line.startswith("["):
            module_entries.append(current_entry)
            current_entry = None
            continue
    if current_entry is not None:
        module_entries.append(current_entry)
    return module_entries


def _is_importable_root(path: Path) -> bool:
    if not path.is_dir():
        return False
    if any((path / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
        return True
    for entry in path.iterdir():
        if entry.is_dir() and any((entry / init_name).is_file() for init_name in ("__init__.py", "__init__.pyi")):
            return True
    return False


def _iter_top_level_importables(module_root: Path) -> Iterable[str]:
    if not module_root.is_dir():
        return []
    result: list[str] = []
    for entry in module_root.iterdir():
        if entry.name == "__pycache__" or entry.name.endswith((".dist-info", ".egg-info")):
            continue
        if entry.is_dir() and _is_importable_root(entry):
            result.append(entry.name)
        elif entry.is_file() and entry.suffix in (".py", ".pyi", ".so", ".pyd") and entry.stem != "__init__":
            result.append(entry.stem)
    return result


def _iter_extension_python_modules(ext_dir: Path) -> Iterable[tuple[Path, str]]:
    config_path = ext_dir / "config" / "extension.toml"
    if not config_path.is_file():
        return []
    try:
        config = toml.load(config_path)
        python_modules = config.get("python", {}).get("module", [])
        if isinstance(python_modules, dict):
            python_modules = [python_modules]
        module_entries = [item for item in python_modules if isinstance(item, dict)]
    except Exception:
        module_entries = _extract_python_module_entries_from_raw_toml(config_path)

    discovered_modules: list[tuple[Path, str]] = []
    seen: set[tuple[str, str]] = set()
    for entry in module_entries:
        module_root = (ext_dir / entry.get("path", ".")).resolve()
        module_name = entry.get("name", "")
        module_names = [module_name] if module_name else list(_iter_top_level_importables(module_root))
        for resolved_name in module_names:
            if not resolved_name or resolved_name.endswith(".tests"):
                continue
            key = (str(module_root), resolved_name)
            if key in seen:
                continue
            seen.add(key)
            discovered_modules.append((module_root, resolved_name))
    return discovered_modules


def _iter_parent_packages(module_name: str) -> Iterable[tuple[str, ...]]:
    parts = module_name.split(".")
    for depth in range(1, len(parts)):
        yield tuple(parts[:depth])


def _resolve_extension_module_path(module_root: Path, module_name: str) -> Path | None:
    parts = module_name.split(".")
    package_path = module_root.joinpath(*parts)
    if package_path.is_dir():
        return package_path

    module_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.py")
    if module_path.is_file():
        return module_path

    stub_path = module_root.joinpath(*parts[:-1], f"{parts[-1]}.pyi")
    if stub_path.is_file():
        return stub_path

    return None


def _overlay_init_content(package_parts: tuple[str, ...]) -> str:
    if package_parts == ("isaacsim",):
        return ISAACSIM_PACKAGE_MARKER
    return PACKAGE_MARKER


def _ensure_overlay_package(overlay_dir: Path, package_parts: tuple[str, ...]) -> Path:
    package_dir = overlay_dir.joinpath(*package_parts)
    package_dir.mkdir(parents=True, exist_ok=True)
    init_path = package_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(_overlay_init_content(package_parts))
    return package_dir


def _symlink_path(src: Path, dst: Path) -> None:
    if dst.is_symlink():
        if dst.resolve() == src.resolve():
            return
        dst.unlink()
    elif dst.exists():
        return
    dst.symlink_to(src)


def _mirror_extension_module(
    module_root: Path,
    module_name: str,
    all_module_names: set[str],
    *,
    overlay_dir: Path,
) -> None:
    module_source = _resolve_extension_module_path(module_root, module_name)
    if module_source is None:
        return

    parts = module_name.split(".")
    for package_parts in _iter_parent_packages(module_name):
        _ensure_overlay_package(overlay_dir, package_parts)

    if module_source.is_file():
        overlay_file = overlay_dir.joinpath(*parts[:-1], module_source.name)
        overlay_file.parent.mkdir(parents=True, exist_ok=True)
        _symlink_path(module_source, overlay_file)
        return

    target_dir = overlay_dir.joinpath(*parts)
    target_dir.mkdir(parents=True, exist_ok=True)
    for entry in module_source.iterdir():
        if entry.name == "__pycache__":
            continue
        if entry.is_dir():
            child_module_name = f"{module_name}.{entry.name}"
        elif entry.suffix == ".py" and entry.stem != "__init__":
            child_module_name = f"{module_name}.{entry.stem}"
        else:
            child_module_name = ""
        if child_module_name and child_module_name in all_module_names:
            continue
        _symlink_path(entry, target_dir / entry.name)

    init_path = target_dir / "__init__.py"
    if not init_path.exists():
        init_path.write_text(_overlay_init_content(tuple(parts)))


def collect_isaacsim_extension_paths() -> list[Path]:
    import isaacsim  # must be importable from the current venv

    isaacsim_path = Path(os.path.realpath(isaacsim.__file__)).parent
    paths: list[Path] = []

    # Kit side (mirrors isaacsim.__main__.generate_vscode_settings)
    kit_path = isaacsim_path / "kit"

    kernel_py = kit_path / "kernel" / "py"
    if kernel_py.is_dir():
        paths.append(kernel_py)

    for folder in ("exts", "extscore"):
        base = kit_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    # Isaac Sim side
    for folder in ("exts", "extscache", "extsDeprecated", "extsUser"):
        base = isaacsim_path / folder
        for ext_dir in _iter_subdirs(base):
            paths.append(ext_dir)

    # Omniverse global extensions (where many omni.* packages live)
    ov_base = Path.home() / ".local" / "share" / "ov" / "data" / "Kit"
    if ov_base.is_dir():
        # Example layout:
        # ~/.local/share/ov/data/Kit/Isaac-Sim Full/5.1/exts/3/omni.usd-...
        for kit_dir in ov_base.iterdir():
            if not kit_dir.is_dir():
                continue
            for exts_root in kit_dir.rglob("exts"):
                if not exts_root.is_dir():
                    continue
                for layer_dir in exts_root.iterdir():
                    if not layer_dir.is_dir():
                        continue
                    for ext_dir in layer_dir.iterdir():
                        if ext_dir.is_dir():
                            paths.append(ext_dir)

    seen: set[str] = set()
    result: list[Path] = []
    for path in paths:
        normalized = path.resolve()
        normalized_str = str(normalized)
        if normalized_str in seen:
            continue
        seen.add(normalized_str)
        result.append(normalized)
    return result


def build_overlay(
    extension_paths: Iterable[Path],
    overlay_dir: Path,
    *,
    include_module: Callable[[str], bool],
    dry_run: bool,
) -> str:
    extension_modules: list[tuple[Path, str]] = []
    module_names: set[str] = set()
    for ext_path in extension_paths:
        for module_root, module_name in _iter_extension_python_modules(ext_path):
            if not include_module(module_name):
                continue
            module_names.add(module_name)
            extension_modules.append((module_root, module_name))

    relative_overlay_dir = overlay_dir.relative_to(REPO_ROOT).as_posix()
    if dry_run:
        return relative_overlay_dir

    if overlay_dir.exists():
        shutil.rmtree(overlay_dir)
    overlay_dir.mkdir(parents=True, exist_ok=True)

    for module_root, module_name in extension_modules:
        _mirror_extension_module(module_root, module_name, module_names, overlay_dir=overlay_dir)

    return relative_overlay_dir


def _format_ty_path(path: Path | str) -> str:
    path_obj = path if isinstance(path, Path) else Path(path)
    if not path_obj.is_absolute():
        return f"./{path_obj.as_posix()}"
    try:
        return f"./{path_obj.relative_to(REPO_ROOT).as_posix()}"
    except ValueError:
        return path_obj.as_posix()


def render_ty_config(*, ty_roots: list[str], ty_extra_paths: list[str]) -> str:
    lines = [f"# Generated by {SCRIPT_RELATIVE_PATH} for static analysis only.", "", "[environment]", 'python = "./.venv"']

    lines.append("root = [")
    for path in ty_roots:
        lines.append(f'    "{path}",')
    lines.append("]")

    lines.append("extra-paths = [")
    for path in ty_extra_paths:
        lines.append(f'    "{path}",')
    lines.append("]")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Collect Isaac Sim / Omniverse python paths for Pyright and ty.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the generated pyrightconfig.deps.json and ty.toml content without writing them.",
    )
    args = parser.parse_args()

    project_source_roots = collect_project_source_roots()
    isaacsim_extension_paths = collect_isaacsim_extension_paths()

    pyright_overlay_path = build_overlay(
        isaacsim_extension_paths,
        PYRIGHT_OVERLAY_DIR,
        include_module=lambda _: True,
        dry_run=args.dry_run,
    )
    ty_overlay_path = build_overlay(
        isaacsim_extension_paths,
        TY_OVERLAY_DIR,
        include_module=lambda module_name: module_name.split(".", 1)[0] in TY_OVERLAY_TOP_LEVEL_PACKAGES,
        dry_run=args.dry_run,
    )

    pyright_extra_paths = [pyright_overlay_path, *(path.as_posix() for path in project_source_roots), *(path.as_posix() for path in isaacsim_extension_paths)]
    pyright_deps_config = {
        "extends": "pyrightconfig.base.json",
        "extraPaths": pyright_extra_paths,
    }

    ty_roots = [_format_ty_path(path) for path in project_source_roots]
    ty_extra_paths = [_format_ty_path(ty_overlay_path), *(_format_ty_path(path) for path in isaacsim_extension_paths)]
    ty_config = render_ty_config(ty_roots=ty_roots, ty_extra_paths=ty_extra_paths)

    if args.dry_run:
        print("=== pyrightconfig.deps.json ===")
        print(json.dumps(pyright_deps_config, indent=4))
        print()
        print("=== ty.toml ===")
        print(ty_config, end="")
        return

    with PYRIGHT_DEPS_CONFIG_PATH.open("w") as file:
        json.dump(pyright_deps_config, file, indent=4)
    TY_CONFIG_PATH.write_text(ty_config)

    print(f"Wrote {PYRIGHT_DEPS_CONFIG_PATH}")
    print(f"Wrote {TY_CONFIG_PATH}")


if __name__ == "__main__":
    main()
