name: Build, Lint, and Test

on:
  push:
    paths: &build_paths
      - ".clang-format"
      - ".clang-tidy"
      - "native/**"
      - "python/**"
      - "pixi.toml"
      - "pixi.lock"
      - "scripts/build.sh"
      - ".github/actions/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths: *build_paths

permissions:
  contents: read

jobs:
  native:
    name: ${{ matrix.build_type }} amd64 linux
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        build_type: [debug, release]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.67.0
          cache: true
          frozen: true
          activate-environment: true

      - name: Cache BrickSim artifacts
        uses: ./.github/actions/cache-bricksim-artifacts

      - name: Build ${{ matrix.build_type }}
        run: pixi run build-native-${{ matrix.build_type }}

      - name: Lint ${{ matrix.build_type }}
        id: lint
        if: ${{ matrix.build_type == 'release' }}
        continue-on-error: true
        run: pixi run lint-native

      - name: Test ${{ matrix.build_type }}
        id: test
        continue-on-error: true
        run: pixi run test-native-${{ matrix.build_type }}

      - name: Upload ${{ matrix.build_type }} native extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.build_type }}
          path: python/bricksim/core.*.so
          if-no-files-found: ignore

      - name: Fail if lint or test failed
        if: ${{ !(steps.test.outcome == 'success' && (steps.lint.outcome == 'skipped' || steps.lint.outcome == 'success')) }}
        run: exit 1
